<?php
/*
    This file should be included by the project specific config
    as default-config.php.
    And is generated by Gruntfile.
*/
define("BASEPATH", "<%- basePath %>");
define("ALLOW_RELATIVE_FILE_WRITES", <%- allowFileWrites %> ); // Uses a specific absolute base path for reading and writing scenario files.
            // Needed, cause files.vpro.nl doesn't allow file writes in the DocumentRoot

?>